name: Get GitHub Actions IP Ranges

on:
  workflow_dispatch:

jobs:
  get-ip-addresses:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve GitHub Actions IP addresses and save to file
      run: |
        echo "Fetching GitHub Actions IP ranges from https://api.github.com/meta"
        curl -s https://api.github.com/meta | jq '.actions' > github-actions-ips.txt

    - name: Upload the IP ranges file
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-ips
        path: github-actions-ips.txt
